Extension { #name : 'OCIRVisitor' }

{ #category : '*Opal-Simd-Bytecode' }
OCIRVisitor >> visitAddFloat32Vector: anIRAddVector [
]

{ #category : '*Opal-Simd-Bytecode' }
OCIRVisitor >> visitAddFloat64Vector: anIRAddVector [
]

{ #category : '*Opal-Simd-Bytecode' }
OCIRVisitor >> visitPushFloat32ArrayToRegister: pushArrayToRegister [
]

{ #category : '*Opal-Simd-Bytecode' }
OCIRVisitor >> visitPushFloat64ArrayToRegister: pushArrayToRegister [
]

{ #category : '*Opal-Simd-Bytecode' }
OCIRVisitor >> visitStoreFloat32RegisterIntoArray: storeRegisterIntoArray [
]

{ #category : '*Opal-Simd-Bytecode' }
OCIRVisitor >> visitStoreFloat64RegisterIntoArray: storeRegisterIntoArray [
]
